# Generated by Django 3.0.3 on 2020-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20200612_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
