# Generated by Django 3.0.3 on 2020-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20200522_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
