# Generated by Django 3.0.3 on 2020-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20200608_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
